#ifndef REPLY_HPP
# define REPLY_HPP

# define RPL_WELCOME			"001"
# define RPL_YOURHOST			"002"

# define ERR_UNKNOWNCOMMAND		"421"
# define ERR_NOTREGISTERED		"451"
# define ERR_NONICKNAMEGIVEN	"431"
# define ERR_ERRONEUSNICK		"432"
# define ERR_NICKNAMEINUSE		"433"
# define ERR_NEEDMOREPARAMS		"461"
# define ERR_ALREADYREGISTRED	"462"
# define ERR_PASSWDMISMATCH		"464"

# define ERR_NEEDMOREPARAMS		"461"
# define ERR_NOSUCHCHANNEL		"403"
# define ERR_BADCHANNELKEY		"475"
# define ERR_INVITEONLYCHAN		"473"
# define ERR_CHANNELISFULL		"471"

#endif
